### ISSUE TITLE
[BUG] Error: Could not resolve './SamplingScoreGenerators/SamplingScoreGenerator' on Azure Pipelines

### ISSUE THREAD

**Issue by praneetloke** [microsoft/ApplicationInsights-JS#1749]
**Description/Screenshot**

It seems that whenever npm dependencies are restored from a cache I get the following error while trying to build an app that relies on this package. The weird thing is it only seems to fail on Windows agents and never on Linux or macOS.

```
Could not resolve './SamplingScoreGenerators/SamplingScoreGenerator' from node_modules\@microsoft\applicationinsights-channel-js\dist-esm\TelemetryProcessors\Sample.js
error during build renderer:
Error: Could not resolve './SamplingScoreGenerators/SamplingScoreGenerator' from node_modules\@microsoft\applicationinsights-channel-js\dist-esm\TelemetryProcessors\Sample.js
    at error (D:\a\1\s\node_modules\vite\node_modules\rollup\dist\shared\rollup.js:158:30)
    at ModuleLoader.handleResolveId (D:\a\1\s\node_modules\vite\node_modules\rollup\dist\shared\rollup.js:22345:24)
    at D:\a\1\s\node_modules\vite\node_modules\rollup\dist\shared\rollup.js:22319:26
error Command failed with exit code 1.
```

Here's a snippet of my pipeline config:

```yaml
trigger:
  # Enable BatchedCI so every push to master doesn't trigger a new build.
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - src
      - package.json
      - yarn.lock
      - build.config.js
      - scripts/build.js
      - .azure-pipelines/.azure-pipelines.ci.yml

pr: none

variables:
  - name: YARN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.yarn

jobs:
  - job: package
    displayName: Build packages
    strategy:
      matrix:
        Linux:
          OS: ubuntu-latest
        macOS:
          OS: macOS-11
        Windows:
          OS: windows-latest

    pool:
      vmImage: $(OS)

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "16.x"
        displayName: "Install Node.js"

      - task: Cache@2
        inputs:
          key: '"yarn" | "$(Agent.OS)" | yarn.lock'
          restoreKeys: |
            yarn | "$(Agent.OS)"
          path: $(YARN_CACHE_FOLDER)
        displayName: Cache Yarn packages

      - script: yarn --frozen-lockfile
        displayName: "yarn install from frozen lockfile"

      - <run a build>
```

**Steps to Reproduce**

1. Create an Azure Pipelines config that caches npm deps (see example config above)
2. Run the pipeline more than once so that the deps are cached on the first run

 - OS/Browser: N/A
 - SDK Version [e.g. 22]: 2.7.2
 - How you initialized the SDK: N/A

**Expected behavior**

Build script should not fail when deps are restored from cache.

**Additional context**

It seems that someone previously opened an issue for this exact problem previously. See https://github.com/microsoft/ApplicationInsights-JS/issues/1326. But it was closed as the issue author thought it had to do something with their local cache. And now I am having issues with this on a build agent that uses dependency caching. It seems there is some sort of a pattern here for this problem? Not to mention this seems to only happen with Windows build agents.

**Comment by MSNev** [comment]
Hmm, there is nothing special about this class/package vs any of the others and we don't do any special processing.

The only thing that comes to mind (especially as you say it's only happening on windows hosts) would be the path "length" as this class is in `dist-esm/TelemetryProcessors/SamplingScoreGenerators/SamplingScoreGenerator.js` that perhaps once you add the build and `node_modules` path on top of this it might be getting affected by windows underlying 260 character path issue which is cause the cache to fail to restore the full path??.

A couple of things you might be able to try
- [Enable Long Paths in Windows 10, Version 1607, and Later](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later)
- If your using git `git config --system core.longpaths true` or `git config --global core.longpaths true` or `git config core.longpaths true` or just add this setting directly in your `.gitconfig`
```
[core]
longpaths = true
```

**Comment by praneetloke** [comment]
Yeah the long paths was my suspicion as well. Let me see if there is way to enable that for Windows build agents. My local machine is on Windows 11 and I do have that enabled so I have never hit this problem on my local machine.

**Comment by praneetloke** [comment]
So I couldn't find any information about the Windows build agents on Azure Pipelines so I changed my approach a little. It was two-fold. First, change the cached folder to be the `node_modules` folder of my project rather than the yarn cache folder. Second, don't run `yarn install` if the deps cache was restored. The second step while unrelated to the issue, is useful since I am directly restoring the `node_modules` folder and thus don't need a `yarn install` step whereas that was needed before when I would only restore the yarn global cache folder.

So now my new pipeline config is:

```yaml
trigger:
  # Enable BatchedCI so every push to master doesn't trigger a new build.
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - src
      - package.json
      - yarn.lock
      - build.config.js
      - scripts/build.js
      - .azure-pipelines/.azure-pipelines.ci.yml

pr: none

variables:
  - name: YARN_CACHE_FOLDER
    value: $(System.DefaultWorkingDirectory)/node_modules <-- Point to the node_modules folder instead of yarn global cache folder.

jobs:
  - job: package
    displayName: Build packages
    strategy:
      matrix:
        Linux:
          OS: ubuntu-latest
        macOS:
          OS: macOS-11
        Windows:
          OS: windows-latest

    pool:
      vmImage: $(OS)

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "16.x"
        displayName: "Install Node.js"

      - task: Cache@2
        inputs:
          key: '"yarn" | "$(Agent.OS)" | yarn.lock'
          restoreKeys: |
            yarn | "$(Agent.OS)"
          path: $(YARN_CACHE_FOLDER)
          cacheHitVar: CACHE_RESTORED   <--- Set this input so we can access the bool value of whether or not cache was restored in the next step.
        displayName: Cache Yarn packages

      - script: yarn --frozen-lockfile
        condition: ne(variables.CACHE_RESTORED, 'true') <-- Add the condition to skip restoring deps altogether if cache was restored.
        displayName: "yarn install from frozen lockfile"

      - <run a build>
```

I'll close this issue out as well. Hopefully others might find this info helpful for their CI pipelines.
